Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.provision :docker
  config.vm.provision :docker_compose
  config.vm.network "forwarded_port", guest: 27017, host: 27017
  config.vm.provision "shell",
    inline: "docker-compose -f /vagrant/docker-compose-dev.yml up -d",
    run: "always"
end
